import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const PreferencesContext = createContext(null);

const STORAGE_THEME_KEY = 'crm_theme';
const STORAGE_LANGUAGE_KEY = 'crm_language';

const translations = {
  es: {
    // ── Navegación ─────────────────────────────────────────────
    home: 'Inicio',
    projects: 'Proyectos',
    agenda: 'Mi Agenda',
    community: 'Comunidad',
    newsPanel: 'Panel de noticias',
    machinery: 'Maquinaria',
    operators: 'Operadores',
    users: 'Usuarios',
    administration: 'Administracion',
    mainMenu: 'Menu Principal',
    internalPanel: 'Panel Interno',
    collapse: 'Colapsar',
    logout: 'Salir',
    searchPlaceholder: 'Buscar...',
    goToProfile: 'Ir a mi perfil',
    darkMode: 'Modo oscuro',
    lightMode: 'Modo claro',
    language: 'Idioma',
    spanish: 'Espanol',
    english: 'English',

    // ── Acciones comunes ────────────────────────────────────────
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    create: 'Crear',
    add: 'Agregar',
    close: 'Cerrar',
    confirm: 'Confirmar',
    update: 'Actualizar',
    accept: 'Aceptar',
    reject: 'Rechazar',
    remove: 'Quitar',
    apply: 'Aplicar',
    clear: 'Limpiar',
    loading: 'Cargando...',
    sending: 'Enviando...',
    saving: 'Guardando...',
    deleting: 'Eliminando...',
    yes: 'Sí',
    no: 'No',
    all: 'Todos',
    none: 'Ninguno',
    optional: 'opcional',
    required: 'requerido',
    of: 'de',
    in: 'en',
    and: 'y',
    or: 'o',
    by: 'por',
    today: 'Hoy',
    yesterday: 'Ayer',
    tomorrow: 'Mañana',
    more: 'más',
    loadMore: 'Ver más',
    seeAll: 'Ver todos',
    back: 'Volver',
    next: 'Siguiente',
    previous: 'Anterior',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',

    // ── Estados ─────────────────────────────────────────────────
    statusTodo: 'Por hacer',
    statusInProgress: 'En progreso',
    statusDone: 'Hecho',
    statusActive: 'Activo',
    statusPaused: 'En pausa',
    statusClosed: 'Cerrado',
    statusOverdue: 'Vencida',
    statusPending: 'Pendiente',
    statusCompleted: 'Completado',

    // ── Prioridades ──────────────────────────────────────────────
    priorityHigh: 'Alta',
    priorityMedium: 'Media',
    priorityLow: 'Baja',
    priorityCritical: 'Crítica',
    priorityNormal: 'Normal',

    // ── Proyectos ────────────────────────────────────────────────
    projectList: 'Lista',
    projectKanban: 'Kanban',
    projectGantt: 'Gantt',
    projectExport: 'Exportar',
    projectImport: 'Importar',
    projectNewTask: 'Nueva Tarea',
    projectSaveTemplate: 'Guardar Plantilla',
    projectGeneralProgress: 'Progreso general',
    projectMyProgress: 'Mi progreso',
    projectTodo: 'Por hacer',
    projectInProgress: 'En marcha',
    projectDone: 'Hechas',
    projectShowing: 'Mostrando',
    projectTaskSingular: 'tarea',
    projectTaskPlural: 'tareas',
    projectTaskSearch: 'Buscar tareas...',
    projectTaskFilters: 'Filtros de tareas',
    projectTaskFiltersDesc: 'Fecha, prioridad y responsable',
    projectDate: 'Fecha',
    projectPriority: 'Prioridad',
    projectResponsible: 'Responsable',
    projectSelectDate: 'Seleccionar fecha',
    projectAllPriorities: 'Todas las prioridades',
    projectAllResponsibles: 'Todos los responsables',
    projectUnassigned: 'Sin asignar',
    projectNoTasksFound: 'No se encontraron tareas con los filtros actuales',
    projectFilterActive: 'Activo',
    projectFilterPaused: 'En pausa',
    projectFilterClosed: 'Cerrado',
    projectFilterAll: 'Todos',
    projectCalendar: 'Calendario de proyectos',
    projectTimeline: 'Línea de tiempo',

    // ── Tareas ───────────────────────────────────────────────────
    taskTitle: 'Título de la tarea',
    taskTitlePlaceholder: '¿Qué hay que hacer?',
    taskDescription: 'Descripción',
    taskDescriptionPlaceholder: 'Detalles adicionales...',
    taskActivityNumber: 'Número de actividad',
    taskActivityPlaceholder: 'Ej. 10',
    taskAssignedTo: 'Asignado a',
    taskStatus: 'Estado',
    taskPriority: 'Prioridad',
    taskMachine: 'Máquina',
    taskNoMachine: 'Sin máquina',
    taskMachineHint: 'Si la tarea usa maquinaria, enlázala: aparecerá en la ficha de la máquina.',
    taskDuration: 'Duración (inicio - fin)',
    taskStart: 'Inicio',
    taskEnd: 'Fin',
    taskCreatedByYou: 'La agregaste tú',
    taskAssignedToYou: 'Responsable: tú',
    taskAssignedBy: 'Asignó:',
    taskUnassigned: 'Sin asignar',
    taskNoDescription: 'Sin descripción',
    taskEditTitle: 'Editar Tarea',
    taskNewTitle: 'Nueva Tarea',
    taskDeleteConfirm: '¿Eliminar esta tarea?',
    taskOverdue: 'Vencida',
    taskDue: 'Vence',
    taskFilterToday: 'Solo hoy',
    taskFilterAll: 'Todas las tareas',
    taskNoTasks: 'Sin tareas',
    taskAdvance: 'Avanzar',
    taskMoveTask: 'Mover tarea',
    taskAttachments: 'Archivos adjuntos',
    taskComments: 'Comentarios',
    taskAssignedSingular: 'asignada',
    taskAssignedPlural: 'asignadas',
    taskExportTitle: 'Exportar tareas',
    taskDeleted: 'Tarea eliminada',
    taskCreated: 'Tarea creada',
    taskUpdated: 'Tarea actualizada',
    taskImportSuccess: 'Se importaron {count} tarea(s)',
    taskSupportDocuments: 'Documentos de apoyo',
    taskAddFiles: 'Agregar archivos',
    taskSelectFiles: 'Seleccionar archivos',
    taskCreatedBySystem: 'Sistema',
    taskDaySingular: 'día',
    taskDayPlural: 'días',
    taskExportStarted: 'Exportación {type} iniciada',
    taskTemplateDefaultName: '{project} Template',
    taskTemplateSaved: 'Plantilla guardada correctamente',

    // ── Kanban ────────────────────────────────────────────────────
    kanbanTodo: 'Por hacer',
    kanbanInProgress: 'En progreso',
    kanbanDone: 'Completado',
    kanbanEmptyState: 'Sin tareas en esta columna',
    kanbanAddTask: 'Agregar tarea',

    // ── Gantt ─────────────────────────────────────────────────────
    ganttVisualKey: 'Lectura visual',
    ganttTimeline: 'Línea de tiempo con estado, prioridad y riesgo',
    ganttTotal: 'Total',
    ganttInProgress: 'En progreso',
    ganttDone: 'Hechas',
    ganttOverdue: 'Vencidas',
    ganttBarStatus: 'Estado de barra',
    ganttProjectTasks: 'Tareas del proyecto',
    ganttUnassigned: 'Sin asignar',
    ganttGeneralArea: 'Área general',
    ganttShowingTasks: 'Mostrando {count} {tasks} en un rango de {days} días.',
    ganttUnassignedCount: '{count} sin asignar',
    ganttOverdueCount: '{count} vencida',
    ganttOverdueCountPlural: '{count} vencidas',

    // ── Equipo ────────────────────────────────────────────────────
    teamTitle: 'Mi Equipo',
    teamMemberSingular: 'miembro',
    teamMemberPlural: 'miembros',
    teamProjectSingular: 'proyecto',
    teamProjectPlural: 'proyectos',
    teamNoMembers: 'Sin miembros asignados en este proyecto',
    teamNoProjects: 'No tienes proyectos asignados aún.',
    teamSummary: '{members} {memberLabel} en {projects} {projectLabel}',
    teamTasksSingular: 'tarea',
    teamTasksPlural: 'tareas',
    roleAdmin: 'Admin',
    roleMember: 'Miembro',
    areaVentas: 'Ventas',
    areaAlmacen: 'Almacén',
    areaCompras: 'Compras',
    areaAdministracion: 'Administración',
    areaRenta: 'Renta',
    areaTaller: 'Taller',
    areaGeneral: 'General',

    // ── Perfil ────────────────────────────────────────────────────
    profileTitle: 'Perfil del usuario',
    profileSubtitle: 'Administra tu información personal y preferencias.',
    profileNotAvailable: 'Perfil no disponible',
    profileLoadError: 'No pudimos cargar tu perfil',
    profilePersonalInfo: 'Información personal',
    profileAccountData: 'Datos de cuenta',
    profileSave: 'Guardar perfil',
    profileChangePhoto: 'Cambiar foto',
    profileRemovePhoto: 'Quitar foto',
    profileActive: 'Activo',
    profilePending: 'Pendiente',
    profileRelatedProjects: 'Proyectos relacionados',
    profileNoProjects: 'Aún no tienes proyectos vinculados.',
    profileStatsActive: 'Proyectos activos',
    profileStatsTasks: 'Tareas asignadas',
    profileStatsCreated: 'Tareas creadas',
    profileStatsPending: 'Pendientes',
    fieldName: 'Nombre',
    fieldEmail: 'Correo',
    fieldPhone: 'Teléfono',
    fieldPhonePlaceholder: 'Tu número de contacto',
    fieldPosition: 'Puesto',
    fieldPositionPlaceholder: 'Ej. Líder de proyecto',
    fieldBio: 'Biografía',
    fieldBioPlaceholder: 'Cuéntale al equipo sobre ti...',
    fieldArea: 'Área',
    fieldRole: 'Rol',
    fieldRegistration: 'Registro',
    fieldGoogleCalendar: 'Google Calendar',
    fieldNotConnected: 'No conectado',

    // ── Eventos / Agenda ──────────────────────────────────────────
    eventNew: 'Nuevo Evento',
    eventEdit: 'Editar Evento',
    eventDetails: 'Detalles del Evento',
    eventTitleLabel: 'Título del evento',
    eventTitlePlaceholder: '¿De qué trata el evento?',
    eventCategory: 'Categoría',
    eventDescriptionPlaceholder: 'Agenda, contexto o puntos a tratar',
    eventDuration: 'Duración del evento',
    eventSelectTime: 'Seleccionar hora',
    eventFrom: 'Desde',
    eventTo: 'Hasta',
    eventModality: 'Modalidad',
    eventInPerson: 'Presencial',
    eventRemote: 'Virtual',
    eventLinkLabel: 'Enlace de reunión',
    eventLinkInvalid: 'El enlace de reunión no es válido.',
    eventLocation: 'Ubicación',
    eventInstructions: 'Instrucciones de acceso',
    eventLogistics: 'Notas logísticas',
    eventOptionalLink: 'Enlace remoto opcional',
    eventCollaboration: 'Colaboración',
    eventCollaborationDesc: 'Define quién puede ver este evento',
    eventAllTeam: 'Todo el equipo',
    eventSpecificMembers: 'Miembros específicos',
    eventSelectMembers: 'Seleccionar miembros del equipo',
    eventNoMembers: 'No hay otros miembros disponibles',
    eventPublicLabel: 'Evento público',
    eventPublicDesc: 'Este evento aparecerá automáticamente en la agenda de todos.',
    eventConflicts: 'Conflictos detectados',
    eventBusyFrom: 'Ocupado de',
    eventTypeEvent: 'Evento',
    eventTypeMeeting: 'Reunión',
    eventTypeTask: 'Tarea',
    eventSaveButton: 'Guardar evento',
    eventCreateButton: 'Crear evento',
    eventUpdateButton: 'Actualizar evento',
    eventRecurringNoDay: 'Selecciona al menos un día de la semana para el evento recurrente.',
    eventDatePlaceholder: 'Seleccionar fecha',
    eventLinkPlaceholder: 'https://meet.google.com/... o enlace interno',
    eventLocationPlaceholder: 'Sala Creativa, Oficina Norte, etc.',
    eventVirtualAccessPlaceholder: 'Código de acceso, cámara opcional, etc.',
    eventInPersonAccessPlaceholder: 'Recepción, edificio, materiales, etc.',
    eventOptionalRemotePlaceholder: 'Si también tendrá acceso remoto, pega el enlace aquí',
    eventInvalidDateTime: 'Revisa la fecha y hora del evento.',
    eventEndAfterStart: 'La fecha y hora de fin deben ser posteriores al inicio.',
    eventInvalidMeetingLink: 'El enlace de reunión no es válido.',

    agendaToday: 'Hoy',
    agendaMonth: 'Mes',
    agendaWeek: 'Semana',
    agendaDay: 'Día',
    agendaFilter: 'Filtros',
    agendaAllTypes: 'Todo',
    agendaProjects: 'Proyectos',
    agendaTasks: 'Tareas',
    agendaEvents: 'Eventos',
    agendaMeetings: 'Reuniones',
    agendaAllProjects: 'Todos los proyectos',
    agendaScheduled: '{count} elementos programados',
    agendaGoToGoogle: 'Ir a Google Calendar',
    agendaConnect: 'Conectar con Google',
    agendaCalendarFilters: 'Filtros del calendario',
    agendaShowingAll: 'Mostrando los elementos disponibles.',
    agendaShowingContext: 'Contexto: {project}',
    agendaClearProject: 'Limpiar proyecto',
    agendaInvitations: 'Invitaciones pendientes',
    agendaTeamAvailability: 'Disponibilidad de equipo',
    agendaProjectFilterLabel: 'Proyecto',
    agendaChooseProjectRange: 'Escoge un proyecto para ver solo su rango en el calendario.',
    agendaChooseProjectTasks: 'Escoge un proyecto para ver solo sus tareas.',
    agendaProjectFilterContext: 'Este proyecto queda como contexto para los filtros.',
    agendaAllProjectsFilter: 'Todos los proyectos',
    agendaOrganizedBy: 'Organizado por:',
    agendaOrganizer: 'Organiza:',
    agendaAllDay: 'Todo el día',
    agendaItemMoveNone: 'No se encontraron elementos para mover.',
    agendaItemMoveSuccess: 'Se movieron {count} {itemLabel} al nuevo día.',
    agendaItemMoveError: 'No se pudo mover el bloque.',
    agendaTaskMoveSuccess: 'Se movieron {count} {taskLabel} {days} {dayLabel}.',
    agendaTaskMoveError: 'No se pudieron mover las tareas.',
    agendaElementMoveError: 'No se pudo mover el elemento.',
    agendaGoogleConnected: 'Google Calendar conectado correctamente',
    agendaGoogleDisconnected: 'Google Calendar desconectado',
    agendaGoogleConnectError: 'No se pudo conectar Google Calendar',
    agendaGoogleDisconnectError: 'No se pudo desconectar Google Calendar',
    agendaGoogleConnectedWith: 'Conectado con {email}',
    agendaGoogleConnectTitle: 'Conectar Google Calendar',
    agendaAcceptInvitation: 'Aceptar',
    agendaRejectInvitation: 'Rechazar',
    agendaItemEventSingular: 'elemento',
    agendaItemEventPlural: 'elementos',

    // ── Dashboard ─────────────────────────────────────────────────
    dashboardGoodMorning: 'Buenos días',
    dashboardGoodAfternoon: 'Buenas tardes',
    dashboardGoodEvening: 'Buenas noches',
    dashboardProjects: 'Proyectos',
    dashboardPending: 'Pendientes',
    dashboardInProgress: 'En marcha',
    dashboardDone: 'Hechas',
    dashboardTeamActivity: 'Actividad del equipo',
    dashboardTeamActivityDesc: 'Tareas hechas hoy, en curso y pendientes por vencimiento.',
    dashboardDoneToday: 'Hechas hoy',
    dashboardDoing: 'Haciendo',
    dashboardDueToday: 'Faltan hoy',
    dashboardDueWeek: 'Faltan semana',
    dashboardTopProductivity: 'Top Productividad',
    dashboardProjectCalendar: 'Calendario de proyectos',
    dashboardSelectProjectFromDates: 'Selecciona un proyecto desde sus fechas activas.',
    dashboardProjectsOf: 'Proyectos del {date}',
    dashboardActiveProjects: '{count} proyectos activos en esta fecha',
    dashboardTodayLine: 'Línea roja = hoy',
    dashboardVisibleProjects: '{count} proyectos visibles',
    dashboardNoProjectTimeline: 'No hay proyectos con fechas para mostrar en la línea de tiempo.',
    dashboardTeamAvailability: 'Disponibilidad del Equipo',
    dashboardTeamOccupation: 'Ocupación por proyectos (azul) y tareas (verde) por miembro.',
    dashboardCalendarFilters: 'Filtros del calendario',
    dashboardAllProjects: 'Todos los proyectos',
    dashboardCompletedToday: 'Sin completadas hoy',
    dashboardNoCurrent: 'Sin tareas en curso',
    dashboardNoDueToday: 'Sin pendientes de hoy',
    dashboardNoDueWeek: 'Sin pendientes próximos',
    dashboardMyProjects: 'Proyectos en los que participas',
    dashboardUpcoming: 'Próximas a vencer',
    dashboardSeeProjects: 'Ver proyectos',
    dashboardOpenBoard: 'Abrir tablero',
    dashboardFollowTasks: 'Seguir tareas',
    dashboardSeeAgenda: 'Ver agenda',
    dashboardConnectionError: 'Error de conexión',
    dashboardAdminTitle: 'Control Central',
    dashboardAdminSubtitle: 'Supervisión estratégica del equipo',
    dashboardProjectGantt: 'Gantt general de proyectos',
    dashboardFocusedView: 'Vista enfocada en {project}',
    dashboardGlobalView: 'Vista global con fechas y avance de proyectos',
    dashboardExpand: 'Expandir',
    dashboardMinimize: 'Minimizar',
    dashboardOpenProject: 'Abrir proyecto',
    dashboardViewBoard: 'Ver tablero',
    dashboardTimelineMinimized: 'El gantt está minimizado. Puedes expandirlo cuando necesites revisar la línea de tiempo.',
    dashboardBoardCalendars: 'Calendarios del tablero',
    dashboardBoardCalendarsToggle: 'Alterna entre el calendario de proyectos y la disponibilidad del equipo.',
    dashboardProjectCalendarDesc: 'Selecciona un proyecto desde sus fechas activas.',
    dashboardTeamAvailabilityDesc: 'Visualiza la ocupación del equipo por proyectos y tareas.',
    dashboardSectionMinimized: 'Esta sección está minimizada. Puedes expandirla para revisar proyectos o disponibilidad del equipo.',
    dashboardProjectProgress: 'Progreso de Proyectos',
    dashboardRecentActivity: 'Flujo Reciente de Actividad',
    dashboardGoProjects: 'Ir a proyectos',
    dashboardPerWeek: 'por semana',
    dashboardTodayWeek: 'Hoy / Semana',
    dashboardCompletedShort: 'hechas',
    dashboardInProgressShort: 'en curso',
    dashboardDueShort: 'hoy',
    dashboardShowingMemberItems: 'Mostrando los elementos disponibles del miembro.',
    dashboardSelectedProjectContext: 'Contexto: {project}',
    dashboardChooseProjectRange: 'Escoge un proyecto para ver solo su rango.',
    dashboardChooseProjectTasks: 'Escoge un proyecto para ver solo sus tareas.',
    dashboardProjectContextFilters: 'Este proyecto queda como contexto para los filtros.',
    dashboardMoveTaskPrompt: '¿Mover esta tarea cuántos días?',
    dashboardMoveTaskNone: 'No se encontraron tareas para mover en este bloque.',
    dashboardMoveTaskSuccess: 'Se movieron {count} {taskLabel} {days} {dayLabel}.',
    dashboardMoveTaskError: 'No se pudieron mover las tareas.',
    dashboardMovePlusOne: 'Mover +1 día',
    dashboardMovePlusTwo: 'Mover +2 días',
    dashboardMoveChooseAmount: 'Elegir cantidad...',
    dashboardTasksLabel: 'Tareas',
    dashboardMembersCount: '{count} {memberLabel}',

    // ── Notificaciones ─────────────────────────────────────────────
    notificationsTitle: 'Notificaciones',
    notificationsPending: '{count} pendientes por revisar',
    notificationsAllGood: 'Todo al día',
    notificationsMarkAll: 'Marcar todas como leídas',
    notificationsEmpty: 'No tienes notificaciones',

    // ── Usuarios ───────────────────────────────────────────────────
    usersTitle: 'Usuarios',
    usersInvite: 'Invitar usuario',
    usersSearch: 'Buscar usuarios...',
    usersAllRoles: 'Todos los roles',
    usersAllAreas: 'Todas las áreas',
    usersActive: 'Activos',
    usersAll: 'Todos',
    usersSingular: 'usuario',
    usersPlural: 'usuarios',
    usersMember: 'miembro',
    usersAdmin: 'administrador',
    usersNoResults: 'No se encontraron usuarios',

    // ── Proyectos ─────────────────────────────────────────────────
    projectsPageTitle: 'Proyectos',
    projectsPageSubtitle: 'Gestión estratégica y operativa del equipo',
    projectsNewProject: 'Nuevo Proyecto',
    projectsNoProjects: 'No hay proyectos que mostrar.',
    projectsTasksCount: 'tareas',
    projectsDragHint: 'Arrastrar',
    projectsSeeMore: 'Ver más',
    projectsConnectedGoogle: 'Google conectado',
    projectsConnectGoogle: 'Conectar Google',
    projectsConnecting: 'Conectando...',
    projectsDisconnecting: 'Desconectando...',
    agendaFilterFirstDesc: 'Primero elige qué tipo de elementos quieres ver.',
    agendaMoreItems: '+{count} más',
    agendaDrag: 'Arrastrar',
    agendaSeeMore: 'Ver más',

    // ── Project modal ──────────────────────────────────────────────
    projectEditTitle: 'Editar Proyecto',
    projectNewModalTitle: 'Nuevo Proyecto',
    projectFieldName: 'Nombre del proyecto',
    projectFieldNamePlaceholder: 'Ej: Rediseño de Marca',
    projectFieldDescPlaceholder: 'Objetivos y alcance...',
    projectFieldStatus: 'Estado',
    projectFieldArea: 'Área responsable',
    projectFieldMembers: 'Miembros de las áreas seleccionadas',
    projectFieldCalendar: 'Calendario de responsables',
    projectFieldDocuments: 'Documentos de apoyo',
    projectTemplateLabel: 'Plantilla base',
    projectTemplatePlaceholder: 'Selecciona una plantilla (opcional)',
    projectTemplateEmpty: 'Aún no hay plantillas guardadas.',
    projectTemplateNoSelect: 'Sin plantilla — el proyecto se crea vacío.',
    projectAdmins: 'Administradores',
    projectNoMembers: 'Sin miembros en esta área.',
    projectAreaSelect: 'Selecciona un área para ver tareas activas.',
    projectNoConflicts: 'Sin tareas activas ni eventos en el rango.',
    projectSaveButton: 'Guardar Proyecto',
    projectLoadMoreTasks: 'Ver más tareas ({count} restantes)',
    projectCheckingCalendar: 'Revisando agenda...',
    projectTemplateTasksBase: '{count} tareas base, con prioridades, dependencias y fechas relativas. Al guardar el proyecto, esa estructura se crea automáticamente.',
    projectDateNoEnd: 'Sin fecha fin',
    projectBlockedTask: 'Tarea ocupada',
    projectActiveProject: 'Proyecto activo',
    projectDefaultDescription: 'Gestión operativa del proyecto y seguimiento de hitos.',
    projectPickArea: 'Selecciona al menos un área.',
    projectDateRangeError: 'La fecha fin debe ser posterior a la fecha inicio.',
    projectMemberRangeConflict: 'El rango seleccionado cruza con tareas activas de los miembros.',
    projectMemberLabel: 'Miembro',
    projectHasBusyItems: 'Tiene tareas/eventos: {items}',
    projectMemberSelected: 'OK',
    projectMemberInProject: 'En proyecto',
    projectStartDate: 'Fecha inicio',
    projectEndDate: 'Fecha fin',
    projectAddFiles: 'Agregar archivos',
    projectSelectFiles: 'Seleccionar archivos',
    projectDeleteConfirm: '¿Eliminar "{name}"?',
    projectDeleted: 'Proyecto eliminado',
    projectNoResultsTitle: 'No se encontraron proyectos',
    projectNoResultsSubtitle: 'Comienza creando uno nuevo o cambia el filtro.',

    // ── Users ──────────────────────────────────────────────────────
    usersManageTitle: 'Gestión de Usuarios',
    usersManageSubtitle: 'Administra el acceso y las invitaciones del equipo.',
    usersActiveMembers: 'Miembros activos',
    usersInvitationsTab: 'Invitaciones',
    usersTableMember: 'Miembro',
    usersTableArea: 'Área',
    usersTableRole: 'Rol',
    usersTableRegister: 'Registro',
    usersTableStatus: 'Estado',
    usersTableActions: 'Acciones',
    usersStatusActive: 'Activo',
    usersStatusInactive: 'Inactivo',
    usersStatusPending: 'Pendiente',
    usersStatusAccepted: 'Aceptada',
    usersCancelInvitation: 'Cancelar invitación',
    usersActivityOf: 'Actividad de {name}',
    usersNoActivityData: 'Sin datos de actividad.',
    usersActivityDone: 'Hechas',
    usersActivityNoDone: 'Sin completadas',
    usersActivityDoing: 'Haciendo',
    usersActivityNoCurrent: 'Sin tareas en curso',
    usersActivityDueToday: 'Faltan hoy',
    usersActivityNoDue: 'Sin pendientes',
    usersActivityDueWeek: 'Faltan semana',
    usersActivityNoDueWeek: 'Sin pendientes próximos',
    usersActivityByProject: 'Por proyecto',
    usersNoActiveMembers: 'No hay miembros activos.',
    usersInviteTitle: 'Invitar Usuario',
    usersInviteSubtitle: 'Se enviará un correo con el enlace de registro.',
    usersInviteNameLabel: 'Nombre del usuario',
    usersInviteNamePlaceholder: 'Ej. Juan Pérez',
    usersInviteEmailLabel: 'Correo electrónico',
    usersInviteEmailPlaceholder: 'juan@empresa.com',
    usersInviteSend: 'Enviar invitación',
    usersInviteSending: 'Enviando...',
    usersEditTitle: 'Editar Miembro',
    usersEditSubtitle: 'Actualiza la información del usuario.',
    usersRegShort: 'Reg:',
    usersActivity: 'Actividad',
    usersBusyWith: 'Ocupado con',
    usersTaskOccupied: 'Tarea ocupada',
    usersProjectActive: 'Proyecto activo',
    usersDateNoEnd: 'Sin fecha fin',
  },

  en: {
    // ── Navigation ─────────────────────────────────────────────
    home: 'Home',
    projects: 'Projects',
    agenda: 'My Agenda',
    community: 'Community',
    newsPanel: 'News board',
    machinery: 'Machinery',
    operators: 'Operators',
    users: 'Users',
    administration: 'Administration',
    mainMenu: 'Main Menu',
    internalPanel: 'Internal Panel',
    collapse: 'Collapse',
    logout: 'Log out',
    searchPlaceholder: 'Search...',
    goToProfile: 'Go to my profile',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    language: 'Language',
    spanish: 'Spanish',
    english: 'English',

    // ── Common actions ──────────────────────────────────────────
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    add: 'Add',
    close: 'Close',
    confirm: 'Confirm',
    update: 'Update',
    accept: 'Accept',
    reject: 'Reject',
    remove: 'Remove',
    apply: 'Apply',
    clear: 'Clear',
    loading: 'Loading...',
    sending: 'Sending...',
    saving: 'Saving...',
    deleting: 'Deleting...',
    yes: 'Yes',
    no: 'No',
    all: 'All',
    none: 'None',
    optional: 'optional',
    required: 'required',
    of: 'of',
    in: 'in',
    and: 'and',
    or: 'or',
    by: 'by',
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',
    more: 'more',
    loadMore: 'Load more',
    seeAll: 'See all',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',

    // ── Statuses ────────────────────────────────────────────────
    statusTodo: 'To do',
    statusInProgress: 'In progress',
    statusDone: 'Done',
    statusActive: 'Active',
    statusPaused: 'Paused',
    statusClosed: 'Closed',
    statusOverdue: 'Overdue',
    statusPending: 'Pending',
    statusCompleted: 'Completed',

    // ── Priorities ───────────────────────────────────────────────
    priorityHigh: 'High',
    priorityMedium: 'Medium',
    priorityLow: 'Low',
    priorityCritical: 'Critical',
    priorityNormal: 'Normal',

    // ── Projects ─────────────────────────────────────────────────
    projectList: 'List',
    projectKanban: 'Kanban',
    projectGantt: 'Gantt',
    projectExport: 'Export',
    projectImport: 'Import',
    projectNewTask: 'New Task',
    projectSaveTemplate: 'Save Template',
    projectGeneralProgress: 'General progress',
    projectMyProgress: 'My progress',
    projectTodo: 'To do',
    projectInProgress: 'In progress',
    projectDone: 'Done',
    projectShowing: 'Showing',
    projectTaskSingular: 'task',
    projectTaskPlural: 'tasks',
    projectTaskSearch: 'Search tasks...',
    projectTaskFilters: 'Task filters',
    projectTaskFiltersDesc: 'Date, priority and assignee',
    projectDate: 'Date',
    projectPriority: 'Priority',
    projectResponsible: 'Assignee',
    projectSelectDate: 'Select date',
    projectAllPriorities: 'All priorities',
    projectAllResponsibles: 'All assignees',
    projectUnassigned: 'Unassigned',
    projectNoTasksFound: 'No tasks matched the current filters',
    projectFilterActive: 'Active',
    projectFilterPaused: 'Paused',
    projectFilterClosed: 'Closed',
    projectFilterAll: 'All',
    projectCalendar: 'Project calendar',
    projectTimeline: 'Timeline',

    // ── Tasks ─────────────────────────────────────────────────────
    taskTitle: 'Task title',
    taskTitlePlaceholder: 'What needs to be done?',
    taskDescription: 'Description',
    taskDescriptionPlaceholder: 'Additional details...',
    taskActivityNumber: 'Activity number',
    taskActivityPlaceholder: 'e.g. 10',
    taskAssignedTo: 'Assigned to',
    taskStatus: 'Status',
    taskPriority: 'Priority',
    taskMachine: 'Machine',
    taskNoMachine: 'No machine',
    taskMachineHint: 'If this task uses machinery, link it: it will show on the machine record.',
    taskDuration: 'Duration (start – end)',
    taskStart: 'Start',
    taskEnd: 'End',
    taskCreatedByYou: 'You added it',
    taskAssignedToYou: 'Assignee: you',
    taskAssignedBy: 'Assigned by:',
    taskUnassigned: 'Unassigned',
    taskNoDescription: 'No description',
    taskEditTitle: 'Edit Task',
    taskNewTitle: 'New Task',
    taskDeleteConfirm: 'Delete this task?',
    taskOverdue: 'Overdue',
    taskDue: 'Due',
    taskFilterToday: 'Today only',
    taskFilterAll: 'All tasks',
    taskNoTasks: 'No tasks',
    taskAdvance: 'Advance',
    taskMoveTask: 'Move task',
    taskAttachments: 'Attachments',
    taskComments: 'Comments',
    taskAssignedSingular: 'assigned',
    taskAssignedPlural: 'assigned',
    taskExportTitle: 'Export tasks',
    taskDeleted: 'Task deleted',
    taskCreated: 'Task created',
    taskUpdated: 'Task updated',
    taskImportSuccess: 'Imported {count} task(s)',
    taskSupportDocuments: 'Supporting documents',
    taskAddFiles: 'Add files',
    taskSelectFiles: 'Select files',
    taskCreatedBySystem: 'System',
    taskDaySingular: 'day',
    taskDayPlural: 'days',
    taskExportStarted: '{type} export started',
    taskTemplateDefaultName: '{project} Template',
    taskTemplateSaved: 'Template saved successfully',

    // ── Kanban ────────────────────────────────────────────────────
    kanbanTodo: 'To do',
    kanbanInProgress: 'In progress',
    kanbanDone: 'Done',
    kanbanEmptyState: 'No tasks in this column',
    kanbanAddTask: 'Add task',

    // ── Gantt ─────────────────────────────────────────────────────
    ganttVisualKey: 'Visual key',
    ganttTimeline: 'Timeline with status, priority and risk',
    ganttTotal: 'Total',
    ganttInProgress: 'In progress',
    ganttDone: 'Done',
    ganttOverdue: 'Overdue',
    ganttBarStatus: 'Bar status',
    ganttProjectTasks: 'Project tasks',
    ganttUnassigned: 'Unassigned',
    ganttGeneralArea: 'General area',
    ganttShowingTasks: 'Showing {count} {tasks} over a {days}-day range.',
    ganttUnassignedCount: '{count} unassigned',
    ganttOverdueCount: '{count} overdue',
    ganttOverdueCountPlural: '{count} overdue',

    // ── Team ──────────────────────────────────────────────────────
    teamTitle: 'My Team',
    teamMemberSingular: 'member',
    teamMemberPlural: 'members',
    teamProjectSingular: 'project',
    teamProjectPlural: 'projects',
    teamNoMembers: 'No members assigned to this project',
    teamNoProjects: 'You have no projects assigned yet.',
    teamSummary: '{members} {memberLabel} across {projects} {projectLabel}',
    teamTasksSingular: 'task',
    teamTasksPlural: 'tasks',
    roleAdmin: 'Admin',
    roleMember: 'Member',
    areaVentas: 'Sales',
    areaAlmacen: 'Warehouse',
    areaCompras: 'Purchasing',
    areaAdministracion: 'Administration',
    areaRenta: 'Rentals',
    areaTaller: 'Workshop',
    areaGeneral: 'General',

    // ── Profile ───────────────────────────────────────────────────
    profileTitle: 'User profile',
    profileSubtitle: 'Manage your personal information and preferences.',
    profileNotAvailable: 'Profile unavailable',
    profileLoadError: 'Could not load your profile',
    profilePersonalInfo: 'Personal information',
    profileAccountData: 'Account details',
    profileSave: 'Save profile',
    profileChangePhoto: 'Change photo',
    profileRemovePhoto: 'Remove photo',
    profileActive: 'Active',
    profilePending: 'Pending',
    profileRelatedProjects: 'Related projects',
    profileNoProjects: 'You have no linked projects yet.',
    profileStatsActive: 'Active projects',
    profileStatsTasks: 'Assigned tasks',
    profileStatsCreated: 'Created tasks',
    profileStatsPending: 'Pending',
    fieldName: 'Name',
    fieldEmail: 'Email',
    fieldPhone: 'Phone',
    fieldPhonePlaceholder: 'Your contact number',
    fieldPosition: 'Position',
    fieldPositionPlaceholder: 'e.g. Project Lead',
    fieldBio: 'Bio',
    fieldBioPlaceholder: 'Tell the team about yourself...',
    fieldArea: 'Area',
    fieldRole: 'Role',
    fieldRegistration: 'Registered',
    fieldGoogleCalendar: 'Google Calendar',
    fieldNotConnected: 'Not connected',

    // ── Events / Agenda ───────────────────────────────────────────
    eventNew: 'New Event',
    eventEdit: 'Edit Event',
    eventDetails: 'Event Details',
    eventTitleLabel: 'Event title',
    eventTitlePlaceholder: 'What is this event about?',
    eventCategory: 'Category',
    eventDescriptionPlaceholder: 'Agenda, context or talking points',
    eventDuration: 'Event duration',
    eventSelectTime: 'Select time',
    eventFrom: 'From',
    eventTo: 'To',
    eventModality: 'Modality',
    eventInPerson: 'In-person',
    eventRemote: 'Remote',
    eventLinkLabel: 'Meeting link',
    eventLinkInvalid: 'The meeting link is not valid.',
    eventLocation: 'Location',
    eventInstructions: 'Access instructions',
    eventLogistics: 'Logistics notes',
    eventOptionalLink: 'Optional remote link',
    eventCollaboration: 'Collaboration',
    eventCollaborationDesc: 'Define who can see this event',
    eventAllTeam: 'All team',
    eventSpecificMembers: 'Specific members',
    eventSelectMembers: 'Select team members',
    eventNoMembers: 'No other members available',
    eventPublicLabel: 'Public event',
    eventPublicDesc: 'This event will automatically appear in everyone\'s agenda.',
    eventConflicts: 'Conflicts detected',
    eventBusyFrom: 'Busy from',
    eventTypeEvent: 'Event',
    eventTypeMeeting: 'Meeting',
    eventTypeTask: 'Task',
    eventSaveButton: 'Save event',
    eventCreateButton: 'Create event',
    eventUpdateButton: 'Update event',
    eventRecurringNoDay: 'Select at least one weekday for the recurring event.',
    eventDatePlaceholder: 'Select date',
    eventLinkPlaceholder: 'https://meet.google.com/... or internal link',
    eventLocationPlaceholder: 'Creative Room, North Office, etc.',
    eventVirtualAccessPlaceholder: 'Access code, camera optional, etc.',
    eventInPersonAccessPlaceholder: 'Reception, building, materials, etc.',
    eventOptionalRemotePlaceholder: 'If it will also have remote access, paste the link here',
    eventInvalidDateTime: 'Check the event date and time.',
    eventEndAfterStart: 'The end date and time must be after the start.',
    eventInvalidMeetingLink: 'The meeting link is not valid.',

    agendaToday: 'Today',
    agendaMonth: 'Month',
    agendaWeek: 'Week',
    agendaDay: 'Day',
    agendaFilter: 'Filters',
    agendaAllTypes: 'All',
    agendaProjects: 'Projects',
    agendaTasks: 'Tasks',
    agendaEvents: 'Events',
    agendaMeetings: 'Meetings',
    agendaAllProjects: 'All projects',
    agendaScheduled: '{count} items scheduled',
    agendaGoToGoogle: 'Open Google Calendar',
    agendaConnect: 'Connect with Google',
    agendaCalendarFilters: 'Calendar filters',
    agendaShowingAll: 'Showing all available items.',
    agendaShowingContext: 'Context: {project}',
    agendaClearProject: 'Clear project',
    agendaInvitations: 'Pending invitations',
    agendaTeamAvailability: 'Team availability',
    agendaProjectFilterLabel: 'Project',
    agendaChooseProjectRange: 'Pick a project to see only its range on the calendar.',
    agendaChooseProjectTasks: 'Pick a project to see only its tasks.',
    agendaProjectFilterContext: 'This project stays as context for the filters.',
    agendaAllProjectsFilter: 'All projects',
    agendaOrganizedBy: 'Organized by:',
    agendaOrganizer: 'Organizer:',
    agendaAllDay: 'All day',
    agendaItemMoveNone: 'No items were found to move.',
    agendaItemMoveSuccess: 'Moved {count} {itemLabel} to the new day.',
    agendaItemMoveError: 'The block could not be moved.',
    agendaTaskMoveSuccess: 'Moved {count} {taskLabel} by {days} {dayLabel}.',
    agendaTaskMoveError: 'Tasks could not be moved.',
    agendaElementMoveError: 'The item could not be moved.',
    agendaGoogleConnected: 'Google Calendar connected successfully',
    agendaGoogleDisconnected: 'Google Calendar disconnected',
    agendaGoogleConnectError: 'Google Calendar could not be connected',
    agendaGoogleDisconnectError: 'Google Calendar could not be disconnected',
    agendaGoogleConnectedWith: 'Connected with {email}',
    agendaGoogleConnectTitle: 'Connect Google Calendar',
    agendaAcceptInvitation: 'Accept',
    agendaRejectInvitation: 'Reject',
    agendaItemEventSingular: 'item',
    agendaItemEventPlural: 'items',

    // ── Dashboard ─────────────────────────────────────────────────
    dashboardGoodMorning: 'Good morning',
    dashboardGoodAfternoon: 'Good afternoon',
    dashboardGoodEvening: 'Good evening',
    dashboardProjects: 'Projects',
    dashboardPending: 'Pending',
    dashboardInProgress: 'In progress',
    dashboardDone: 'Done',
    dashboardTeamActivity: 'Team activity',
    dashboardTeamActivityDesc: 'Tasks done today, in progress and due soon.',
    dashboardDoneToday: 'Done today',
    dashboardDoing: 'Doing',
    dashboardDueToday: 'Due today',
    dashboardDueWeek: 'Due this week',
    dashboardTopProductivity: 'Top Productivity',
    dashboardProjectCalendar: 'Project calendar',
    dashboardSelectProjectFromDates: 'Select a project from its active dates.',
    dashboardProjectsOf: 'Projects on {date}',
    dashboardActiveProjects: '{count} active projects on this date',
    dashboardTodayLine: 'Red line = today',
    dashboardVisibleProjects: '{count} visible projects',
    dashboardNoProjectTimeline: 'No projects with dates to show on the timeline.',
    dashboardTeamAvailability: 'Team Availability',
    dashboardTeamOccupation: 'Occupation by projects (blue) and tasks (green) per member.',
    dashboardCalendarFilters: 'Calendar filters',
    dashboardAllProjects: 'All projects',
    dashboardCompletedToday: 'None completed today',
    dashboardNoCurrent: 'No tasks in progress',
    dashboardNoDueToday: 'Nothing due today',
    dashboardNoDueWeek: 'No upcoming tasks',
    dashboardMyProjects: 'Projects you\'re part of',
    dashboardUpcoming: 'Upcoming deadlines',
    dashboardSeeProjects: 'See projects',
    dashboardOpenBoard: 'Open board',
    dashboardFollowTasks: 'Track tasks',
    dashboardSeeAgenda: 'See agenda',
    dashboardConnectionError: 'Connection error',
    dashboardAdminTitle: 'Central Control',
    dashboardAdminSubtitle: 'Strategic oversight for the team',
    dashboardProjectGantt: 'General project gantt',
    dashboardFocusedView: 'Focused view on {project}',
    dashboardGlobalView: 'Global view with project dates and progress',
    dashboardExpand: 'Expand',
    dashboardMinimize: 'Minimize',
    dashboardOpenProject: 'Open project',
    dashboardViewBoard: 'View board',
    dashboardTimelineMinimized: 'The gantt is minimized. Expand it whenever you need to review the timeline.',
    dashboardBoardCalendars: 'Board calendars',
    dashboardBoardCalendarsToggle: 'Switch between the project calendar and team availability.',
    dashboardProjectCalendarDesc: 'Select a project from its active dates.',
    dashboardTeamAvailabilityDesc: 'Visualize team workload by projects and tasks.',
    dashboardSectionMinimized: 'This section is minimized. Expand it to review projects or team availability.',
    dashboardProjectProgress: 'Project Progress',
    dashboardRecentActivity: 'Recent Activity Flow',
    dashboardGoProjects: 'Go to projects',
    dashboardPerWeek: 'per week',
    dashboardTodayWeek: 'Today / Week',
    dashboardCompletedShort: 'done',
    dashboardInProgressShort: 'in progress',
    dashboardDueShort: 'due today',
    dashboardShowingMemberItems: 'Showing the member available items.',
    dashboardSelectedProjectContext: 'Context: {project}',
    dashboardChooseProjectRange: 'Pick a project to see only its range.',
    dashboardChooseProjectTasks: 'Pick a project to see only its tasks.',
    dashboardProjectContextFilters: 'This project stays as context for the filters.',
    dashboardMoveTaskPrompt: 'Move this task by how many days?',
    dashboardMoveTaskNone: 'No tasks were found to move in this block.',
    dashboardMoveTaskSuccess: 'Moved {count} {taskLabel} by {days} {dayLabel}.',
    dashboardMoveTaskError: 'Tasks could not be moved.',
    dashboardMovePlusOne: 'Move +1 day',
    dashboardMovePlusTwo: 'Move +2 days',
    dashboardMoveChooseAmount: 'Choose amount...',
    dashboardTasksLabel: 'Tasks',
    dashboardMembersCount: '{count} {memberLabel}',

    // ── Notifications ──────────────────────────────────────────────
    notificationsTitle: 'Notifications',
    notificationsPending: '{count} pending to review',
    notificationsAllGood: 'All caught up',
    notificationsMarkAll: 'Mark all as read',
    notificationsEmpty: 'You have no notifications',

    // ── Users ──────────────────────────────────────────────────────
    usersTitle: 'Users',
    usersInvite: 'Invite user',
    usersSearch: 'Search users...',
    usersAllRoles: 'All roles',
    usersAllAreas: 'All areas',
    usersActive: 'Active',
    usersAll: 'All',
    usersSingular: 'user',
    usersPlural: 'users',
    usersMember: 'member',
    usersAdmin: 'administrator',
    usersNoResults: 'No users found',

    // ── Projects page ──────────────────────────────────────────────
    projectsPageTitle: 'Projects',
    projectsPageSubtitle: 'Strategic and operational team management',
    projectsNewProject: 'New Project',
    projectsNoProjects: 'No projects to show.',
    projectsTasksCount: 'tasks',
    projectsDragHint: 'Drag',
    projectsSeeMore: 'See more',
    projectsConnectedGoogle: 'Google connected',
    projectsConnectGoogle: 'Connect Google',
    projectsConnecting: 'Connecting...',
    projectsDisconnecting: 'Disconnecting...',
    agendaFilterFirstDesc: 'First choose what type of items you want to see.',
    agendaMoreItems: '+{count} more',
    agendaDrag: 'Drag',
    agendaSeeMore: 'See more',

    // ── Project modal ──────────────────────────────────────────────
    projectEditTitle: 'Edit Project',
    projectNewModalTitle: 'New Project',
    projectFieldName: 'Project name',
    projectFieldNamePlaceholder: 'e.g. Brand Redesign',
    projectFieldDescPlaceholder: 'Goals and scope...',
    projectFieldStatus: 'Status',
    projectFieldArea: 'Responsible area',
    projectFieldMembers: 'Members of selected areas',
    projectFieldCalendar: 'Assignee calendar',
    projectFieldDocuments: 'Supporting documents',
    projectTemplateLabel: 'Base template',
    projectTemplatePlaceholder: 'Select a template (optional)',
    projectTemplateEmpty: 'No templates saved yet.',
    projectTemplateNoSelect: 'No template — project will be created empty.',
    projectAdmins: 'Administrators',
    projectNoMembers: 'No members in this area.',
    projectAreaSelect: 'Select an area to see active tasks.',
    projectNoConflicts: 'No active tasks or events in this range.',
    projectSaveButton: 'Save Project',
    projectLoadMoreTasks: 'Load more ({count} remaining)',
    projectCheckingCalendar: 'Checking schedule...',
    projectTemplateTasksBase: '{count} base tasks, with priorities, dependencies, and relative dates. When you save the project, that structure is created automatically.',
    projectDateNoEnd: 'No end date',
    projectBlockedTask: 'Busy task',
    projectActiveProject: 'Active project',
    projectDefaultDescription: 'Operational project management and milestone tracking.',
    projectPickArea: 'Select at least one area.',
    projectDateRangeError: 'The end date must be after the start date.',
    projectMemberRangeConflict: 'The selected range overlaps active member tasks.',
    projectMemberLabel: 'Member',
    projectHasBusyItems: 'Has tasks/events: {items}',
    projectMemberSelected: 'OK',
    projectMemberInProject: 'In project',
    projectStartDate: 'Start date',
    projectEndDate: 'End date',
    projectAddFiles: 'Add files',
    projectSelectFiles: 'Select files',
    projectDeleteConfirm: 'Delete "{name}"?',
    projectDeleted: 'Project deleted',
    projectNoResultsTitle: 'No projects found',
    projectNoResultsSubtitle: 'Start by creating one or change the filter.',

    // ── Users ──────────────────────────────────────────────────────
    usersManageTitle: 'User Management',
    usersManageSubtitle: 'Manage team access and invitations.',
    usersActiveMembers: 'Active members',
    usersInvitationsTab: 'Invitations',
    usersTableMember: 'Member',
    usersTableArea: 'Area',
    usersTableRole: 'Role',
    usersTableRegister: 'Registered',
    usersTableStatus: 'Status',
    usersTableActions: 'Actions',
    usersStatusActive: 'Active',
    usersStatusInactive: 'Inactive',
    usersStatusPending: 'Pending',
    usersStatusAccepted: 'Accepted',
    usersCancelInvitation: 'Cancel invitation',
    usersActivityOf: 'Activity for {name}',
    usersNoActivityData: 'No activity data.',
    usersActivityDone: 'Done',
    usersActivityNoDone: 'None completed',
    usersActivityDoing: 'Doing',
    usersActivityNoCurrent: 'No tasks in progress',
    usersActivityDueToday: 'Due today',
    usersActivityNoDue: 'None pending',
    usersActivityDueWeek: 'Due this week',
    usersActivityNoDueWeek: 'No upcoming tasks',
    usersActivityByProject: 'By project',
    usersNoActiveMembers: 'No active members.',
    usersInviteTitle: 'Invite User',
    usersInviteSubtitle: 'An email with the registration link will be sent.',
    usersInviteNameLabel: 'User name',
    usersInviteNamePlaceholder: 'e.g. John Smith',
    usersInviteEmailLabel: 'Email address',
    usersInviteEmailPlaceholder: 'john@company.com',
    usersInviteSend: 'Send invitation',
    usersInviteSending: 'Sending...',
    usersEditTitle: 'Edit Member',
    usersEditSubtitle: 'Update the user\'s information.',
    usersRegShort: 'Reg:',
    usersActivity: 'Activity',
    usersBusyWith: 'Busy with',
    usersTaskOccupied: 'Busy task',
    usersProjectActive: 'Active project',
    usersDateNoEnd: 'No end date',
  },
};

export const PreferencesProvider = ({ children }) => {
  const [theme, setTheme] = useState(() => localStorage.getItem(STORAGE_THEME_KEY) || 'light');
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_LANGUAGE_KEY) || 'es');

  useEffect(() => {
    localStorage.setItem(STORAGE_THEME_KEY, theme);
    document.documentElement.dataset.theme = theme;
    document.documentElement.style.colorScheme = theme;
  }, [theme]);

  useEffect(() => {
    localStorage.setItem(STORAGE_LANGUAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    theme,
    setTheme,
    language,
    setLanguage,
    locale: language === 'en' ? 'en-US' : 'es-MX',
    t: (key, vars = {}) => {
      const str = translations[language]?.[key] ?? translations.es[key] ?? key;
      return Object.entries(vars).reduce((s, [k, v]) => s.replace(`{${k}}`, String(v)), str);
    },
  }), [theme, language]);

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  );
};

export const usePreferences = () => {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error('usePreferences must be used inside <PreferencesProvider>');
  return context;
};
